### ISSUE TITLE
branding on auth pages

### ISSUE THREAD

**Issue by D3PSI** [D3PSI/lumium#123]
**Is your feature request related to a problem? Please describe.**
we currently have functional, but pretty boring login/signup etc pages. we'd like to add some custom lumium styling to them

**Describe the solution you'd like**
we can play around a bit here, maybe play around with putting some logo animation in the background, using granim.js, whatever looks good i guess.

**Describe alternatives you've considered**
-
**Additional context**
-

**Comment by ReddixT** [comment]
added with this commit https://github.com/D3PSI/lumium/pull/140/commits/9f834677f77815e04ce501b38236095ba4e716bd

**Comment by D3PSI** [comment]
@ReddixT no need to close manually, you can just link the PR and when the PR gets merged, the issue will get closed automatically :)
