### ISSUE TITLE
Hosting: Vercel would be a nice alternative to Heruko. Although both are nice solutions.

### ISSUE THREAD

**Issue by theArgex** [D3PSI/lumium#153]
See title :p

well okay take this link    
# ( °□°) ︵ [ ๅǝɔɹǝʌ](https://vercel.com/)

**Comment by D3PSI** [comment]
yes, we considered vercel. we also use it for other projects. but i'm not sure vercel has the same capabilities as we use in out heroku deployments, we have a redis, we build frontend modules using rust and the wasm-bindgen toolchain, we use postgres as our main data store, and all is scalable individually for next to no cost... i don't see any reason currently to switch. although heroku has increased their prices just two days ago, so let's see where we land. might start to be cheaper to have the heroku org own all of the pipelines etc from a billing perspective at this point

**Comment by ReddixT** [comment]
closing this as irrelavent we will stick with heroku
