### ISSUE TITLE
cypress tests are unstable

### ISSUE THREAD

**Issue by D3PSI** [D3PSI/lumium#170]
**Describe the bug**
cypress tests sometimes work, sometimes they don't. up to now we only had this issue on github actions, but i've just noticed it when running on my local as well. so this is concerning

**To Reproduce**
1. `yarn test`

**Expected behavior**
-

**Screenshots**
![image](https://user-images.githubusercontent.com/35960796/207148509-7d2911e2-25b3-42df-bf62-20d00a93b633.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ReddixT** [comment]
might have been solved with https://github.com/D3PSI/lumium/commit/ebb79f1da5a1811a0d1fd27ac6f9d911417749a3

**Comment by D3PSI** [comment]
> might have been solved with [ebb79f1](https://github.com/D3PSI/lumium/commit/ebb79f1da5a1811a0d1fd27ac6f9d911417749a3)

i guess we'll find out

**Comment by D3PSI** [comment]
i have not observed this again and am therefore closing this as completed
