### ISSUE TITLE
inconsistent cypress tests

### ISSUE THREAD

**Issue by ReddixT** [D3PSI/lumium#42]
**Describe the bug**
Delete Account behavior varies and often makes the cypressscripts fail

**To Reproduce**
1. run cypresstests

**Expected behavior**
no fail

**Comment by D3PSI** [comment]
no fail

**Comment by ReddixT** [comment]
Fixed with https://github.com/D3PSI/lumium/commit/bea98be0473a4c46e76a6cc21cee595a7a9439ab
